source 'https://rubygems.org'

gem 'bundler-audit', :git => 'https://github.com/mccabe615/bundler-audit.git'
gem 'httparty'
gem 'docker-api', :require => 'docker'
gem 'git'


#test for bundle-audit
#gem 'rails', '3.2.12'
