---
http_interactions:
- request:
    method: post
    uri: unix:///var/run/docker.sock/v1.12/auth
    body:
      encoding: UTF-8
      string: '{"username":"tlunter","password":"************","email":"tlunter@gmail.com","serveraddress":"https://index.docker.io/v1/"}'
    headers:
      User-Agent:
      - Swipely/Docker-API 1.11.2
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      Content-Type:
      - application/json
      Date:
      - Thu, 26 Jun 2014 20:42:19 GMT
      Content-Length:
      - '29'
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        {"Status":"Login Succeeded"}
    http_version: 
  recorded_at: Thu, 26 Jun 2014 20:42:19 GMT
recorded_with: VCR 2.9.2
